name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit (optional)
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # See action.yml for all options
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}
          config_display: large
          repositories_forks: yes
          repositories_affiliations: owner, collaborator
          plugin_languages: yes
          plugin_languages_ignored: html, css, json, xml
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 8
          plugin_languages_sections: most-used, recently-used
          plugin_languages_indepth: no
          plugin_languages_recent_load: 500
          plugin_languages_recent_days: 0
          commits_authoring: matteias.collet@bluewin.ch, .user.login, Collet
          plugin_stars: yes
          plugin_stars_limit: 4
          plugin_habits: no
          plugin_habits_from: 500
          plugin_habits_days: 7
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          config_timezone: Europe/Paris
